name: Autotests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome
        run: sudo apt install google-chrome-stable

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
