name: Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose deployment target
        required: true
        default: Run second test
        type: choice
        options:
          - Run first test
          - Run second test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome
        run: sudo apt install google-chrome-stable

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run first test
        if: ${{ github.event.inputs.deployment_target == 'Run first test' }}
        run: pytest -vs test_button_exist.py::test_button_exist

      - name: Run second test
        if: ${{ github.event.inputs.deployment_target == 'Run second test' }}
        run: pytest -vs test_button_exist.py::test_second_button_exist
